<center>
<h4>Universidad Nacional de Córdoba - Facultad de Matemática, Astronomía, Física y Computación</h4>
<h3>Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones</h3>
</center>

<h1> Práctico 4 </h1>
<h3> Aprendizaje Supervisado - 2019 </h3>

Trabajaremos con el mismo dataset utilizado en curación de datos (deben utilizar el dataset que se encuentra con los datos modificados o bien aplicar los mismos métodos del trabajo anterior para contar con datos válidos)

El dataset cuenta con X features, siendo las más importantes

* Componente: Indica a que componente pertenece la muestra
* Horas Funcionamiento: Indica la cantidad de horas de funcionamiento del camión (sería como el kilometraje de los camiones)
* Horas del Aceite: Representa la cantidad de horas de utilización del aceite (este dato es importante dado que a medida que, a mayor horas de uso del aceite, el mismo comienza a desgastarse)
* Resultado: (El laboratorio indica si la muestra de aceite está Bien = 1, Regular=2, Mal=3)
* St: Presencia de Hollin en el Aceite
* Al:  Presencia de Aluminio en el Aceite
* Fe	 Presencia de Hierro en el Aceite
* Si  Presencia de Silicio en el Aceite
* Na	 Presencia de Sodio en el Aceite
* Visco: Viscosidad del aceite
* Fecha de Análisis: Indica cuando fué analizada la muestra por el laboratorio

**Limpieza datos**

In [73]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [74]:
# Set seed
np.random.seed(42)

In [75]:
# Load data
dataset = pd.read_csv('datasets/OilDataSetCuracion.csv', parse_dates=["Fecha de Análisis"])

In [76]:
# Show data types
dataset.dtypes

Equipo                          object
Componente                      object
Id                             float64
Resultado                      float64
Horas Funcionamiento           float64
Horas del Aceite               float64
Fecha de Análisis       datetime64[ns]
B                              float64
Nit                            float64
Oxi                            float64
Sul                            float64
St                             float64
V                              float64
Al                             float64
Cr                             float64
Cu                             float64
Fe                             float64
Pb                             float64
Mo                             float64
Ni                             float64
Sn                             float64
Si                             float64
K                              float64
Na                             float64
W                               object
F                               object
A                               object
ISO                             object
PQI                            float64
Ba                             float64
Ca                             float64
Mg                             float64
Mn                             float64
P                              float64
Zn                             float64
Ag                             float64
Ti                             float64
V40                            float64
V100                           float64
TBN                            float64
TAN                            float64
ISO14                          float64
ISO4                           float64
ISO6                           float64
dtype: object

In [77]:
# Show columns name
dataset.columns

Index(['Equipo', 'Componente', 'Id', 'Resultado', 'Horas Funcionamiento',
       'Horas del Aceite', 'Fecha de Análisis', 'B', 'Nit', 'Oxi', 'Sul', 'St',
       'V', 'Al', 'Cr', 'Cu', 'Fe', 'Pb', 'Mo', 'Ni', 'Sn', 'Si', 'K', 'Na',
       'W', 'F', 'A', 'ISO', 'PQI', 'Ba', 'Ca', 'Mg', 'Mn', 'P', 'Zn', 'Ag',
       'Ti', 'V40', 'V100', 'TBN', 'TAN', 'ISO14', 'ISO4', 'ISO6'],
      dtype='object')

In [78]:
# Rename columns
dataset.rename(columns={'Horas Funcionamiento': 'Horas_Funcionamiento', 
                        'Horas del Aceite': 'Horas_del_Aceite',
                       'Fecha de Análisis': 'Fecha_de_Analisis'}, inplace=True)

In [79]:
# Show components, and check component that has more data
dataset.groupby('Componente').describe()

                         Id                                                    \
                      count           mean           std       min        25%
Componente
Convertidor          2074.0  242588.281099  35909.564953  174454.0  209448.50
Diferencial Trasero  2099.0  241857.993807  36130.659806  155978.0  208912.00
Mando Final TD       1952.0  243010.372951  36119.796257  155973.0  210947.75
Mando Final TI       1948.0  242754.750513  36022.621682  155980.0  210727.00
Masa Derecha         1961.0  242437.385518  36122.993104  155976.0  209604.00
Masa Izquierda       1966.0  242674.654629  36067.432264  155977.0  209867.00
Motor                2487.0  243563.730197  34654.431452  156982.0  212632.00
Radiador              660.0  264346.050000  16447.146210  235953.0  250494.75
Sist de Dirección    2013.0  243470.320914  35382.063329  155974.0  212118.00
Sist. Hidráulico     2140.0  243842.215421  35264.958397  155972.0  212642.50
Transmisión          2132.0  242141.277674  35792.647457  156983.0  209561.25

                                                   Resultado            ...  \
                          50%        75%       max     count      mean  ...
Componente                                                              ...
Convertidor          247541.5  273798.50  299709.0    2074.0  1.258438  ...
Diferencial Trasero  247179.0  272993.50  299663.0    2099.0  1.340162  ...
Mando Final TD       247521.5  274717.25  299698.0    1952.0  1.355533  ...
Mando Final TI       247171.0  274115.50  299484.0    1948.0  1.348049  ...
Masa Derecha         246322.0  273850.00  299608.0    1961.0  1.404895  ...
Masa Izquierda       247013.5  274079.50  299714.0    1966.0  1.554425  ...
Motor                251103.0  272410.00  299786.0    2487.0  1.554483  ...
Radiador             264353.5  276868.25  299386.0     660.0  1.251515  ...
Sist de Dirección    249625.0  273782.00  299604.0    2013.0  1.337308  ...
Sist. Hidráulico     249992.0  273769.50  299702.0    2140.0  1.769159  ...
Transmisión          246906.0  273098.75  299712.0    2132.0  1.281895  ...

                     ISO4          ISO6                                   \
                      75%   max   count       mean       std   min   25%
Componente
Convertidor          21.0  23.0  1605.0  17.081620  1.540862  13.0  16.0
Diferencial Trasero  22.0  23.0  1699.0  17.909947  1.549958  14.0  17.0
Mando Final TD       22.0  23.0  1576.0  17.772843  1.587786  14.0  17.0
Mando Final TI       22.0  23.0  1570.0  17.802548  1.509433  14.0  17.0
Masa Derecha         22.0  24.0  1425.0  18.489123  1.366761  15.0  17.0
Masa Izquierda       23.0  24.0  1358.0  18.765832  1.495642  15.0  18.0
Motor                 NaN   NaN     0.0        NaN       NaN   NaN   NaN
Radiador              NaN   NaN     0.0        NaN       NaN   NaN   NaN
Sist de Dirección    20.0  23.0  1608.0  17.536692  1.717409  14.0  16.0
Sist. Hidráulico     22.0  24.0  1428.0  17.890056  1.503963  14.0  17.0
Transmisión          21.0  24.0  1660.0  17.139157  1.549048  14.0  16.0


                      50%   75%   max
Componente
Convertidor          17.0  18.0  22.0
Diferencial Trasero  18.0  19.0  22.0
Mando Final TD       18.0  19.0  22.0
Mando Final TI       18.0  19.0  22.0
Masa Derecha         18.0  19.0  23.0
Masa Izquierda       19.0  20.0  23.0
Motor                 NaN   NaN   NaN
Radiador              NaN   NaN   NaN
Sist de Dirección    17.0  19.0  22.0
Sist. Hidráulico     18.0  19.0  22.0
Transmisión          17.0  18.0  23.0

[11 rows x 296 columns]

In [80]:
# Load engines dataset
engines = dataset[dataset.Componente == 'Motor']

In [81]:
engines.head()

,Equipo,Componente,Id,Resultado,Horas_Funcionamiento,Horas_del_Aceite,Fecha_de_Analisis,B,Nit,Oxi,...,Zn,Ag,Ti,V40,V100,TBN,TAN,ISO14,ISO4,ISO6
3,1355,Motor,273586.0,3.0,21950.0,409.0,2019-02-20,51.0,9.0,22.0,...,1089.0,0.0,0.0,NaN,13.7,9.1,NaN,NaN,NaN,NaN
12,1357,Motor,156982.0,1.0,27876.0,263.0,2017-11-05,NaN,6.0,9.0,...,1246.0,0.0,0.0,NaN,14.0,NaN,NaN,NaN,NaN,NaN
29,1356,Motor,295810.0,3.0,28295.0,NaN,2019-05-17,47.0,10.0,25.0,...,1122.0,0.0,0.0,NaN,14.2,10.4,NaN,NaN,NaN,NaN
49,1355,Motor,283998.0,3.0,22729.0,380.0,2019-04-03,100.0,6.0,12.0,...,1334.0,0.0,0.0,NaN,14.1,9.8,NaN,NaN,NaN,NaN
50,1355,Motor,294825.0,2.0,23153.0,424.0,2019-05-12,105.0,8.0,20.0,...,1331.0,0.0,0.0,NaN,14.3,9.6,NaN,NaN,NaN,NaN

In [82]:
engines.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Id,2487.0,243563.730197,34654.431452,156982.00,212632.000,251103.0,272410.00,299786.00
Resultado,2487.0,1.554483,0.772716,1.00,1.000,1.0,2.00,3.00
Horas_Funcionamiento,2487.0,37315.413752,10981.269208,106.00,33112.500,40169.0,45164.50,52143.00
Horas_del_Aceite,2367.0,303.175750,129.075592,0.00,251.000,282.0,356.00,976.00
B,2430.0,84.800988,38.864568,0.00,52.000,87.8,111.00,492.00
Nit,2342.0,6.734266,1.805881,0.00,6.000,7.0,8.00,23.00
Oxi,2342.0,16.683980,1.874634,4.00,16.000,17.0,18.00,25.00
Sul,2342.0,21.356806,1.854626,8.00,21.000,21.2,22.00,29.00
St,2103.0,34.785069,15.963726,0.00,25.000,33.0,42.00,131.00
V,2431.0,0.370917,0.777268,0.00,0.000,0.0,0.10,5.00
Al,2431.0,1.821102,1.312649,0.00,1.000,2.0,2.00,37.10
Cr,2432.0,0.179112,0.388660,0.00,0.000,0.0,0.10,8.40
Cu,2431.0,9.750309,77.347857,0.00,1.000,1.6,3.00,1366.00
Fe,2432.0,23.382730,16.008713,0.00,13.875,19.0,29.00,128.00
Pb,2431.0,0.408721,0.716127,0.00,0.000,0.0,1.00,9.00
Mo,2431.0,59.334225,11.389921,0.00,50.000,61.0,66.00,196.00
Ni,2431.0,0.323817,0.465842,0.00,0.000,0.0,1.00,3.00
Sn,2431.0,0.117976,0.303291,0.00,0.000,0.0,0.10,2.00
Si,2431.0,6.015508,63.925335,0.00,2.000,3.0,4.00,1721.00
K,2431.0,8.509132,89.413246,0.00,0.000,1.0,1.00,3017.00
Na,2430.0,18.130741,120.220316,0.00,3.000,5.0,8.00,3511.00
PQI,2433.0,9.751336,11.730291,0.00,2.000,6.0,13.00,216.00
Ba,2431.0,0.039572,0.171238,0.00,0.000,0.0,0.00,2.20
Ca,2431.0,1611.836693,300.909013,10.00,1345.000,1483.0,1912.00,4000.00
Mg,2419.0,541.795205,196.790949,0.00,386.000,418.0,765.00,1033.00
Mn,2431.0,0.171699,0.391406,0.00,0.000,0.0,0.00,4.00
P,2431.0,1071.597696,72.615795,3.00,1042.000,1074.0,1108.00,1505.00
Zn,2431.0,1303.246812,99.788505,4.00,1250.000,1288.0,1335.00,2077.00
Ag,2431.0,0.028712,0.146784,0.00,0.000,0.0,0.00,4.00
Ti,2431.0,0.037680,0.189507,0.00,0.000,0.0,0.00,6.80
V40,350.0,13.995686,0.368784,13.22,13.730,13.9,14.22,15.57
V100,2052.0,14.675634,0.815501,2.60,14.400,14.6,14.90,37.70
TBN,1716.0,9.515851,0.851084,0.80,9.200,9.7,10.00,11.80
TAN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ISO14,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ISO4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ISO6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
# Delete columns without data
del_col = ['A', 'F', 'W', 'ISO', 'TAN', 'ISO14', 'ISO4', 'ISO6', 'TBN']
def delete_col(ds):
    for c in del_col:
        ds.drop(c, axis=1, inplace=True)
    return ds

In [84]:
engines = delete_col(engines)

In [85]:
engines.head()

,Equipo,Componente,Id,Resultado,Horas_Funcionamiento,Horas_del_Aceite,Fecha_de_Analisis,B,Nit,Oxi,...,Ba,Ca,Mg,Mn,P,Zn,Ag,Ti,V40,V100
3,1355,Motor,273586.0,3.0,21950.0,409.0,2019-02-20,51.0,9.0,22.0,...,0.0,1663.0,463.0,2.0,880.0,1089.0,0.0,0.0,NaN,13.7
12,1357,Motor,156982.0,1.0,27876.0,263.0,2017-11-05,NaN,6.0,9.0,...,0.0,4000.0,23.0,0.0,1048.0,1246.0,0.0,0.0,NaN,14.0
29,1356,Motor,295810.0,3.0,28295.0,NaN,2019-05-17,47.0,10.0,25.0,...,0.0,1889.0,466.0,1.0,903.0,1122.0,0.0,0.0,NaN,14.2
49,1355,Motor,283998.0,3.0,22729.0,380.0,2019-04-03,100.0,6.0,12.0,...,0.0,2045.0,410.0,1.0,1129.0,1334.0,0.0,0.0,NaN,14.1
50,1355,Motor,294825.0,2.0,23153.0,424.0,2019-05-12,105.0,8.0,20.0,...,1.0,2021.0,434.0,1.0,1128.0,1331.0,0.0,0.0,NaN,14.3

In [86]:
# Count NaN by columns
columns = ['Equipo', 'Componente', 'Id', 'Resultado', 'Horas_Funcionamiento',
       'Horas_del_Aceite', 'Fecha_de_Analisis', 'B', 'Nit', 'Oxi', 'Sul', 'St',
       'V', 'Al', 'Cr', 'Cu', 'Fe', 'Pb', 'Mo', 'Ni', 'Sn', 'Si', 'K', 'Na',
       'PQI', 'Ba', 'Ca', 'Mg', 'Mn', 'P', 'Zn', 'Ag',
       'Ti', 'V40', 'V100']
for c in columns:
    null_b = engines[engines[c].isnull()][c]
    print(c + ' tiene nulos: ' + str(null_b.shape))

Equipo tiene nulos: (0,)
Componente tiene nulos: (0,)
Id tiene nulos: (0,)
Resultado tiene nulos: (0,)
Horas_Funcionamiento tiene nulos: (0,)
Horas_del_Aceite tiene nulos: (120,)
Fecha_de_Analisis tiene nulos: (0,)
B tiene nulos: (57,)
Nit tiene nulos: (145,)
Oxi tiene nulos: (145,)
Sul tiene nulos: (145,)
St tiene nulos: (384,)
V tiene nulos: (56,)
Al tiene nulos: (56,)
Cr tiene nulos: (55,)
Cu tiene nulos: (56,)
Fe tiene nulos: (55,)
Pb tiene nulos: (56,)
Mo tiene nulos: (56,)
Ni tiene nulos: (56,)
Sn tiene nulos: (56,)
Si tiene nulos: (56,)
K tiene nulos: (56,)
Na tiene nulos: (57,)
PQI tiene nulos: (54,)
Ba tiene nulos: (56,)
Ca tiene nulos: (56,)
Mg tiene nulos: (68,)
Mn tiene nulos: (56,)
P tiene nulos: (56,)
Zn tiene nulos: (56,)
Ag tiene nulos: (56,)
Ti tiene nulos: (56,)
V40 tiene nulos: (2137,)
V100 tiene nulos: (435,)

Manage V40 Y V100 to Binary Matrix:

In [87]:
engines['V40'].replace(engines[engines['V40'].notnull()]['V40'], 1, inplace=True)

In [88]:
v40notnull1 = engines[engines['V40']== 1.0]['V40']
v40notnull1.shape

(350,)

In [89]:
engines['V40'].fillna(0, inplace=True)

In [90]:
v40isnull0 = engines[engines['V40']== 0.0]['V40']
v40isnull0.shape

(2137,)

In [91]:
engines['V100'].replace(engines[engines['V100'].notnull()]['V100'], 1, inplace=True)

In [92]:
v100notnull1 = engines[engines['V100'] == 1.0]['V100']
v100notnull1.shape

(2052,)

In [93]:
engines['V100'].fillna(0, inplace=True)

In [94]:
v100isnull0 = engines[engines['V100']==0]['V100']
v100isnull0.shape

(435,)

In [95]:
# Count NaN by columns
columns = ['Equipo', 'Componente', 'Id', 'Resultado', 'Horas_Funcionamiento',
       'Horas_del_Aceite', 'Fecha_de_Analisis', 'B', 'Nit', 'Oxi', 'Sul', 'St',
       'V', 'Al', 'Cr', 'Cu', 'Fe', 'Pb', 'Mo', 'Ni', 'Sn', 'Si', 'K', 'Na',
       'PQI', 'Ba', 'Ca', 'Mg', 'Mn', 'P', 'Zn', 'Ag',
       'Ti', 'V40', 'V100']
for c in columns:
    null_b = engines[engines[c].isnull()][c]
    print(c + ' tiene nulos: ' + str(null_b.shape))

Equipo tiene nulos: (0,)
Componente tiene nulos: (0,)
Id tiene nulos: (0,)
Resultado tiene nulos: (0,)
Horas_Funcionamiento tiene nulos: (0,)
Horas_del_Aceite tiene nulos: (120,)
Fecha_de_Analisis tiene nulos: (0,)
B tiene nulos: (57,)
Nit tiene nulos: (145,)
Oxi tiene nulos: (145,)
Sul tiene nulos: (145,)
St tiene nulos: (384,)
V tiene nulos: (56,)
Al tiene nulos: (56,)
Cr tiene nulos: (55,)
Cu tiene nulos: (56,)
Fe tiene nulos: (55,)
Pb tiene nulos: (56,)
Mo tiene nulos: (56,)
Ni tiene nulos: (56,)
Sn tiene nulos: (56,)
Si tiene nulos: (56,)
K tiene nulos: (56,)
Na tiene nulos: (57,)
PQI tiene nulos: (54,)
Ba tiene nulos: (56,)
Ca tiene nulos: (56,)
Mg tiene nulos: (68,)
Mn tiene nulos: (56,)
P tiene nulos: (56,)
Zn tiene nulos: (56,)
Ag tiene nulos: (56,)
Ti tiene nulos: (56,)
V40 tiene nulos: (0,)
V100 tiene nulos: (0,)

In [96]:
#Delete NaN values
engines = engines.dropna()
engines.shape

(1981, 35)

In [97]:
# Columnas de interes para prediccion - Large Dataset
values_cols = ['Resultado', 'Horas_del_Aceite', 'B', 'Nit', 'Oxi', 'Sul', 'St',
       'V', 'Al', 'Cr', 'Cu', 'Fe', 'Pb', 'Mo', 'Ni', 'Sn', 'Si', 'K', 'Na',
       'PQI', 'Ba', 'Ca', 'Mg', 'Mn', 'P', 'Zn', 'Ag',
       'Ti', 'V40', 'V100']
values_engine = engines[values_cols]

In [98]:
values_engine.head()

,Resultado,Horas_del_Aceite,B,Nit,Oxi,Sul,St,V,Al,Cr,...,Ba,Ca,Mg,Mn,P,Zn,Ag,Ti,V40,V100
3,3.0,409.0,51.0,9.0,22.0,25.0,57.0,1.0,3.0,1.0,...,0.0,1663.0,463.0,2.0,880.0,1089.0,0.0,0.0,0.0,1.0
49,3.0,380.0,100.0,6.0,12.0,17.0,28.0,0.0,2.0,1.0,...,0.0,2045.0,410.0,1.0,1129.0,1334.0,0.0,0.0,0.0,1.0
50,2.0,424.0,105.0,8.0,20.0,26.0,52.0,0.0,2.0,1.0,...,1.0,2021.0,434.0,1.0,1128.0,1331.0,0.0,0.0,0.0,1.0
57,2.0,82.0,108.0,6.0,18.0,24.0,14.0,0.0,2.0,0.0,...,0.0,1808.0,433.0,0.0,1046.0,1181.0,0.0,0.0,0.0,1.0
74,3.0,399.0,106.0,7.0,14.0,19.0,42.0,1.0,4.0,1.0,...,0.0,1994.0,434.0,1.0,1153.0,1346.0,0.0,0.0,0.0,1.0

**Clasificacion**

#### Vamos a probar con diferentes modelos

In [99]:
y = values_engine['Resultado']
X = values_engine.drop('Resultado', axis=1)

In [100]:
from sklearn.model_selection import cross_val_score
# Algorithms
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from ml.visualization import plot_confusion_matrix, plot_learning_curve

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.0)

In [102]:
# Stochastic Gradient Descent (SGD)
mod = linear_model.SGDClassifier(max_iter=5, tol=None)
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_sgd = round(scores.mean(), 2)

Scores: [0.69849246 0.27135678 0.63819095 0.6969697  0.62121212 0.63131313
 0.65656566 0.61616162 0.34010152 0.37055838]
Mean: 0.5540922321704406
Standard Deviation: 0.152504289556939

In [103]:
# Random Forest
mod = RandomForestClassifier(n_estimators=100)
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_random_forest = round(scores.mean(), 2)

Scores: [0.86432161 0.83417085 0.81909548 0.84343434 0.85353535 0.88888889
 0.87373737 0.83838384 0.83756345 0.81218274]
Mean: 0.8465313930571691
Standard Deviation: 0.02267511998121298

In [104]:
# Logistic Regression
mod = LogisticRegression(solver='lbfgs', multi_class='auto')
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_log = round(scores.mean(), 2)

Scores: [0.77889447 0.77386935 0.80904523 0.80808081 0.7979798  0.82323232
 0.80808081 0.76262626 0.78680203 0.8071066 ]
Mean: 0.7955717674667755
Standard Deviation: 0.018193090421937196

In [105]:
# K Nearest Neighbor
mod = KNeighborsClassifier(n_neighbors = 5)
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_knn = round(scores.mean(), 2)

Scores: [0.70351759 0.67839196 0.69346734 0.7020202  0.71212121 0.68686869
 0.71212121 0.68181818 0.71573604 0.68527919]
Mean: 0.6971341607798002
Standard Deviation: 0.013057910005003656

In [106]:
# Gaussian Naive Bayes
mod = GaussianNB()
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_gaussian = round(scores.mean(), 2)

Scores: [0.77889447 0.75376884 0.7638191  0.74242424 0.78282828 0.74242424
 0.77272727 0.75252525 0.7106599  0.7715736 ]
Mean: 0.7571645207527664
Standard Deviation: 0.020628157233652772

In [107]:
# Perceptron
mod = Perceptron(max_iter=15)
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_perceptron = round(scores.mean(), 2)

Scores: [0.48743719 0.63819095 0.64824121 0.17171717 0.37373737 0.6969697
 0.70707071 0.64141414 0.68527919 0.28426396]
Mean: 0.5334321584850882
Standard Deviation: 0.1833871611289262

In [108]:
# Linear Support Vector Machine
mod = LinearSVC()
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_linear_svc = round(scores.mean(), 2)

Scores: [0.34673367 0.74371859 0.74874372 0.76767677 0.71212121 0.78787879
 0.51010101 0.74242424 0.73604061 0.73096447]
Mean: 0.6826403076243649
Standard Deviation: 0.13365616103343195

In [109]:
# Decision Tree
mod = DecisionTreeClassifier()
scores = cross_val_score(mod, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())
acc_decision_tree = round(scores.mean(), 2)

Scores: [0.8040201  0.81909548 0.78894472 0.79292929 0.76262626 0.7979798
 0.7979798  0.77777778 0.78172589 0.7715736 ]
Mean: 0.7894652723186253
Standard Deviation: 0.015760699881726924

In [110]:
results = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 
              'Decision Tree'],
    'Score': [acc_linear_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_decision_tree]})
result_df = results.sort_values(by='Score', ascending=False)
result_df = result_df.set_index('Score')
result_df.head(9)

                            Model
Score
0.85                Random Forest
0.80          Logistic Regression
0.79                Decision Tree
0.76                  Naive Bayes
0.70                          KNN
0.68      Support Vector Machines
0.55   Stochastic Gradient Decent
0.53                   Perceptron

#### Con Random Forest obtuvimos el valor más alto de accuracy entre todos los modelos que probamos. Ahora intentaremos encontrar los hipeperámetros que lo hagan funcionar mejor aun.

In [116]:
param_grid = { "criterion" : ["gini", "entropy"], "min_samples_leaf" : [1, 2, 3,4, 5, 10, 25, 50, 70], "min_samples_split" : [2, 3, 4, 5, 10, 12, 16, 18, 25, 35], "n_estimators": [10, 50, 100, 400, 700, 1000, 1500]}
from sklearn.model_selection import GridSearchCV, cross_val_score
#rf = RandomForestClassifier(n_estimators=100, max_features='auto', oob_score=True, random_state=1, n_jobs=-1)
rf = RandomForestClassifier(max_features='auto', oob_score=True, random_state=1, n_jobs=-1)
clf = GridSearchCV(estimator=rf, param_grid=param_grid, n_jobs=-1)
clf.fit(X_train, y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=-1,
            oob_score=True, random_state=1, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'criterion': ['gini', 'entropy'], 'min_samples_leaf': [1, 2, 3, 4, 5, 10, 25, 50, 70], 'min_samples_split': [2, 3, 4, 5, 10, 12, 16, 18, 25, 35], 'n_estimators': [10, 50, 100, 400, 700, 1000, 1500]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [117]:
clf.best_params_

{'criterion': 'gini',
 'min_samples_leaf': 1,
 'min_samples_split': 10,
 'n_estimators': 1000}

In [118]:
# Random Forest
random_forest = RandomForestClassifier(criterion = "gini", 
                                       min_samples_leaf = 1, 
                                       min_samples_split = 10,   
                                       n_estimators=1000, 
                                       max_features='auto', 
                                       oob_score=True, 
                                       random_state=1, 
                                       n_jobs=-1)

scores = cross_val_score(random_forest, X_train, y_train, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())

Scores: [0.8490566  0.83647799 0.81761006 0.88679245 0.81012658 0.87974684
 0.82278481 0.84810127 0.88607595 0.84177215]
Mean: 0.8478544701854949
Standard Deviation: 0.02669962821449919

#### Con Decision Tree la mejor accuracy que habiamos obtenido fue 82,70% mientras que con Random Forest obtuvimos una accuracy promedio de 84,78% +/- 2,66%